directories:
  output: setup
  buildResources: build
appId: com.makerlab.makerblockly
productName: MakerBlockly
publish:
  - provider: github
    repo: MakerBlockly
    owner: devilthanh
    token: <stripped sensitive data>
    private: false
    publishAutoUpdate: true
extraFiles:
  - filter:
      - resources/arduino-cli.exe
win:
  target: NSIS
  icon: icon.ico
nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  installerIcon: icon.ico
  uninstallerIcon: icon.ico
electronVersion: 8.2.0
